/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ActivityDistributionDataWithAdditionalDataAllOfActivityDistribution : The distribution of activities related to the organization grouped by the user ID



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityDistributionDataWithAdditionalDataAllOfActivityDistribution {
    #[serde(rename = "ASSIGNED_TO_USER_ID", skip_serializing_if = "Option::is_none")]
    pub assigned_to_user_id: Option<Box<crate::models::ActivityDistributionDataWithAdditionalDataAllOfActivityDistributionAssignedToUserId>>,
}

impl ActivityDistributionDataWithAdditionalDataAllOfActivityDistribution {
    /// The distribution of activities related to the organization grouped by the user ID
    pub fn new() -> ActivityDistributionDataWithAdditionalDataAllOfActivityDistribution {
        ActivityDistributionDataWithAdditionalDataAllOfActivityDistribution {
            assigned_to_user_id: None,
        }
    }
}


