/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ActivityDistributionDataWithAdditionalDataAllOfActivityDistributionAssignedToUserIdActivities : The count of activities related to the user grouped by activity type



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityDistributionDataWithAdditionalDataAllOfActivityDistributionAssignedToUserIdActivities {
    /// The count of activities related to a specific type
    #[serde(rename = "ACTIVITY_TYPE_NAME", skip_serializing_if = "Option::is_none")]
    pub activity_type_name: Option<i32>,
}

impl ActivityDistributionDataWithAdditionalDataAllOfActivityDistributionAssignedToUserIdActivities {
    /// The count of activities related to the user grouped by activity type
    pub fn new() -> ActivityDistributionDataWithAdditionalDataAllOfActivityDistributionAssignedToUserIdActivities {
        ActivityDistributionDataWithAdditionalDataAllOfActivityDistributionAssignedToUserIdActivities {
            activity_type_name: None,
        }
    }
}


