/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddActivityResponse200AdditionalData {
    /// This field will be deprecated
    #[serde(rename = "updates_story_id", skip_serializing_if = "Option::is_none")]
    pub updates_story_id: Option<i32>,
}

impl AddActivityResponse200AdditionalData {
    pub fn new() -> AddActivityResponse200AdditionalData {
        AddActivityResponse200AdditionalData {
            updates_story_id: None,
        }
    }
}


