/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddDealParticipantRequest {
    /// The ID of the person
    #[serde(rename = "person_id")]
    pub person_id: i32,
}

impl AddDealParticipantRequest {
    pub fn new(person_id: i32) -> AddDealParticipantRequest {
        AddDealParticipantRequest {
            person_id,
        }
    }
}


