/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddOrUpdateGoalResponse200DataGoal {
    /// The ID of the goal
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The ID of the creator of the goal
    #[serde(rename = "owner_id", skip_serializing_if = "Option::is_none")]
    pub owner_id: Option<i32>,
    /// The title of the goal
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Box<crate::models::AddOrUpdateGoalResponse200DataGoalType>>,
    #[serde(rename = "assignee", skip_serializing_if = "Option::is_none")]
    pub assignee: Option<Box<crate::models::AddOrUpdateGoalResponse200DataGoalAssignee>>,
    /// The interval of the goal
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<String>,
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<Box<crate::models::AddOrUpdateGoalResponse200DataGoalDuration>>,
    #[serde(rename = "expected_outcome", skip_serializing_if = "Option::is_none")]
    pub expected_outcome: Option<Box<crate::models::AddOrUpdateGoalResponse200DataGoalExpectedOutcome>>,
    /// Whether the goal is currently active or not
    #[serde(rename = "is_active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    /// The IDs of the reports that belong to the goal
    #[serde(rename = "report_ids", skip_serializing_if = "Option::is_none")]
    pub report_ids: Option<Vec<String>>,
}

impl AddOrUpdateGoalResponse200DataGoal {
    pub fn new() -> AddOrUpdateGoalResponse200DataGoal {
        AddOrUpdateGoalResponse200DataGoal {
            id: None,
            owner_id: None,
            title: None,
            r#type: None,
            assignee: None,
            interval: None,
            duration: None,
            expected_outcome: None,
            is_active: None,
            report_ids: None,
        }
    }
}


