/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddLeadLabelRequest {
    /// The name of the lead label
    #[serde(rename = "name")]
    pub name: String,
    /// The color of the label. Only a subset of colors can be used.
    #[serde(rename = "color")]
    pub color: Color,
}

impl AddLeadLabelRequest {
    pub fn new(name: String, color: Color) -> AddLeadLabelRequest {
        AddLeadLabelRequest {
            name,
            color,
        }
    }
}

/// The color of the label. Only a subset of colors can be used.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Color {
    #[serde(rename = "green")]
    Green,
    #[serde(rename = "blue")]
    Blue,
    #[serde(rename = "red")]
    Red,
    #[serde(rename = "yellow")]
    Yellow,
    #[serde(rename = "purple")]
    Purple,
    #[serde(rename = "gray")]
    Gray,
}

impl Default for Color {
    fn default() -> Color {
        Self::Green
    }
}

