/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AddOrUpdateGoalResponse200DataGoalDuration : The duration of the goal



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddOrUpdateGoalResponse200DataGoalDuration {
    /// The start date of the goal
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,
    /// The end date of the goal
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<String>,
}

impl AddOrUpdateGoalResponse200DataGoalDuration {
    /// The duration of the goal
    pub fn new() -> AddOrUpdateGoalResponse200DataGoalDuration {
        AddOrUpdateGoalResponse200DataGoalDuration {
            start: None,
            end: None,
        }
    }
}


