/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BaseMailThreadAllOfPartiesToInner : Member of a thread



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseMailThreadAllOfPartiesToInner {
    /// ID of the mail thread participant
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Name of the mail thread participant
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Whether the mail thread participant was last to send an email
    #[serde(rename = "latest_sent", skip_serializing_if = "Option::is_none")]
    pub latest_sent: Option<bool>,
    /// Email address of the mail thread participant
    #[serde(rename = "email_address", skip_serializing_if = "Option::is_none")]
    pub email_address: Option<String>,
    /// Message time
    #[serde(rename = "message_time", skip_serializing_if = "Option::is_none")]
    pub message_time: Option<f32>,
    /// ID of the linked person
    #[serde(rename = "linked_person_id", skip_serializing_if = "Option::is_none")]
    pub linked_person_id: Option<i32>,
    /// Email of the linked person
    #[serde(rename = "linked_person_name", skip_serializing_if = "Option::is_none")]
    pub linked_person_name: Option<String>,
    /// ID of the mail message party
    #[serde(rename = "mail_message_party_id", skip_serializing_if = "Option::is_none")]
    pub mail_message_party_id: Option<i32>,
    /// Linked Organization ID
    #[serde(rename = "linked_organization_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub linked_organization_id: Option<Option<i32>>,
}

impl BaseMailThreadAllOfPartiesToInner {
    /// Member of a thread
    pub fn new() -> BaseMailThreadAllOfPartiesToInner {
        BaseMailThreadAllOfPartiesToInner {
            id: None,
            name: None,
            latest_sent: None,
            email_address: None,
            message_time: None,
            linked_person_id: None,
            linked_person_name: None,
            mail_message_party_id: None,
            linked_organization_id: None,
        }
    }
}


