/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BaseRoleRequest : The details of the role



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseRoleRequest {
    /// The ID of the parent role
    #[serde(rename = "parent_role_id", skip_serializing_if = "Option::is_none")]
    pub parent_role_id: Option<i32>,
    /// The name of the role
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl BaseRoleRequest {
    /// The details of the role
    pub fn new() -> BaseRoleRequest {
        BaseRoleRequest {
            parent_role_id: None,
            name: None,
        }
    }
}


