/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CallLogsResponseAdditionalData {
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::FieldsResponse200AllOfAdditionalData>>,
}

impl CallLogsResponseAdditionalData {
    pub fn new() -> CallLogsResponseAdditionalData {
        CallLogsResponseAdditionalData {
            pagination: None,
        }
    }
}


