/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DealNonStrictAllOfCreatorUserId : The creator of the deal



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DealNonStrictAllOfCreatorUserId {
    /// The ID of the deal creator
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The name of the deal creator
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The email of the deal creator
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// If the creator has a picture or not
    #[serde(rename = "has_pic", skip_serializing_if = "Option::is_none")]
    pub has_pic: Option<bool>,
    /// The creator picture hash
    #[serde(rename = "pic_hash", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pic_hash: Option<Option<String>>,
    /// Whether the creator is active or not
    #[serde(rename = "active_flag", skip_serializing_if = "Option::is_none")]
    pub active_flag: Option<bool>,
    /// The ID of the deal creator
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<i32>,
}

impl DealNonStrictAllOfCreatorUserId {
    /// The creator of the deal
    pub fn new() -> DealNonStrictAllOfCreatorUserId {
        DealNonStrictAllOfCreatorUserId {
            id: None,
            name: None,
            email: None,
            has_pic: None,
            pic_hash: None,
            active_flag: None,
            value: None,
        }
    }
}


