/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DealNonStrictWithDetailsAllOfAverageTimeToWon : The average time to win the deal



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DealNonStrictWithDetailsAllOfAverageTimeToWon {
    /// Years
    #[serde(rename = "y", skip_serializing_if = "Option::is_none")]
    pub y: Option<i32>,
    /// Months
    #[serde(rename = "m", skip_serializing_if = "Option::is_none")]
    pub m: Option<i32>,
    /// Days
    #[serde(rename = "d", skip_serializing_if = "Option::is_none")]
    pub d: Option<i32>,
    /// Hours
    #[serde(rename = "h", skip_serializing_if = "Option::is_none")]
    pub h: Option<i32>,
    /// Minutes
    #[serde(rename = "i", skip_serializing_if = "Option::is_none")]
    pub i: Option<i32>,
    /// Seconds
    #[serde(rename = "s", skip_serializing_if = "Option::is_none")]
    pub s: Option<i32>,
    /// The total time in seconds
    #[serde(rename = "total_seconds", skip_serializing_if = "Option::is_none")]
    pub total_seconds: Option<i32>,
}

impl DealNonStrictWithDetailsAllOfAverageTimeToWon {
    /// The average time to win the deal
    pub fn new() -> DealNonStrictWithDetailsAllOfAverageTimeToWon {
        DealNonStrictWithDetailsAllOfAverageTimeToWon {
            y: None,
            m: None,
            d: None,
            h: None,
            i: None,
            s: None,
            total_seconds: None,
        }
    }
}


