/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetDealsSummaryResponse200Data : The summary of deals



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDealsSummaryResponse200Data {
    #[serde(rename = "values_total", skip_serializing_if = "Option::is_none")]
    pub values_total: Option<Box<crate::models::GetDealsSummaryResponse200DataValuesTotal>>,
    #[serde(rename = "weighted_values_total", skip_serializing_if = "Option::is_none")]
    pub weighted_values_total: Option<Box<crate::models::GetDealsSummaryResponse200DataWeightedValuesTotal>>,
    /// The total number of deals
    #[serde(rename = "total_count", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i32>,
    /// The total value of deals converted into the company default currency
    #[serde(rename = "total_currency_converted_value", skip_serializing_if = "Option::is_none")]
    pub total_currency_converted_value: Option<f32>,
    /// The total weighted value of deals converted into the company default currency
    #[serde(rename = "total_weighted_currency_converted_value", skip_serializing_if = "Option::is_none")]
    pub total_weighted_currency_converted_value: Option<f32>,
    /// The total converted value of deals formatted with the company default currency. E.g. US$5,100.96
    #[serde(rename = "total_currency_converted_value_formatted", skip_serializing_if = "Option::is_none")]
    pub total_currency_converted_value_formatted: Option<String>,
    /// The total weighted value of deals formatted with the company default currency. E.g. US$5,100.96
    #[serde(rename = "total_weighted_currency_converted_value_formatted", skip_serializing_if = "Option::is_none")]
    pub total_weighted_currency_converted_value_formatted: Option<String>,
}

impl GetDealsSummaryResponse200Data {
    /// The summary of deals
    pub fn new() -> GetDealsSummaryResponse200Data {
        GetDealsSummaryResponse200Data {
            values_total: None,
            weighted_values_total: None,
            total_count: None,
            total_currency_converted_value: None,
            total_weighted_currency_converted_value: None,
            total_currency_converted_value_formatted: None,
            total_weighted_currency_converted_value_formatted: None,
        }
    }
}


