/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRecentsResponse200DataInnerAnyOf11DataAccessInner {
    #[serde(rename = "app", skip_serializing_if = "Option::is_none")]
    pub app: Option<App>,
    #[serde(rename = "admin", skip_serializing_if = "Option::is_none")]
    pub admin: Option<bool>,
    #[serde(rename = "permission_set_id", skip_serializing_if = "Option::is_none")]
    pub permission_set_id: Option<String>,
}

impl GetRecentsResponse200DataInnerAnyOf11DataAccessInner {
    pub fn new() -> GetRecentsResponse200DataInnerAnyOf11DataAccessInner {
        GetRecentsResponse200DataInnerAnyOf11DataAccessInner {
            app: None,
            admin: None,
            permission_set_id: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum App {
    #[serde(rename = "sales")]
    Sales,
    #[serde(rename = "projects")]
    Projects,
    #[serde(rename = "campaigns")]
    Campaigns,
    #[serde(rename = "global")]
    Global,
    #[serde(rename = "account_settings")]
    AccountSettings,
}

impl Default for App {
    fn default() -> App {
        Self::Sales
    }
}

