/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAssociatedDealsResponse200AllOfRelatedObjects {
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<Box<crate::models::AddActivityResponse200RelatedObjectsOrganization>>,
    #[serde(rename = "person", skip_serializing_if = "Option::is_none")]
    pub person: Option<Box<crate::models::AddActivityResponse200RelatedObjectsPerson>>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<crate::models::GetActivitiesResponse200RelatedObjectsUser>>,
    #[serde(rename = "stage", skip_serializing_if = "Option::is_none")]
    pub stage: Option<Box<crate::models::GetAssociatedDealsResponse200AllOfRelatedObjectsStage>>,
    #[serde(rename = "pipeline", skip_serializing_if = "Option::is_none")]
    pub pipeline: Option<Box<crate::models::GetAssociatedDealsResponse200AllOfRelatedObjectsPipeline>>,
}

impl GetAssociatedDealsResponse200AllOfRelatedObjects {
    pub fn new() -> GetAssociatedDealsResponse200AllOfRelatedObjects {
        GetAssociatedDealsResponse200AllOfRelatedObjects {
            organization: None,
            person: None,
            user: None,
            stage: None,
            pipeline: None,
        }
    }
}


