/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRecentsResponse200DataInnerAnyOf7 {
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<Item>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::BaseOrganizationItem>>,
}

impl GetRecentsResponse200DataInnerAnyOf7 {
    pub fn new() -> GetRecentsResponse200DataInnerAnyOf7 {
        GetRecentsResponse200DataInnerAnyOf7 {
            item: None,
            id: None,
            data: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Item {
    #[serde(rename = "organization")]
    Organization,
}

impl Default for Item {
    fn default() -> Item {
        Self::Organization
    }
}

