/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDays : The moved deals average age in days



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDays {
    /// The moved deals average age across all stages
    #[serde(rename = "across_all_stages", skip_serializing_if = "Option::is_none")]
    pub across_all_stages: Option<i32>,
    /// The moved deals average age by stages
    #[serde(rename = "by_stages", skip_serializing_if = "Option::is_none")]
    pub by_stages: Option<Vec<crate::models::GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDaysByStagesInner>>,
}

impl GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDays {
    /// The moved deals average age in days
    pub fn new() -> GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDays {
        GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDays {
            across_all_stages: None,
            by_stages: None,
        }
    }
}


