/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetOrganizationResponse200AllOfAdditionalDataFollowers : The follower that is associated with the item



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOrganizationResponse200AllOfAdditionalDataFollowers {
    #[serde(rename = "FOLLOWER_USER_ID", skip_serializing_if = "Option::is_none")]
    pub follower_user_id: Option<Box<crate::models::GetOrganizationResponse200AllOfAdditionalDataFollowersFollowerUserId>>,
}

impl GetOrganizationResponse200AllOfAdditionalDataFollowers {
    /// The follower that is associated with the item
    pub fn new() -> GetOrganizationResponse200AllOfAdditionalDataFollowers {
        GetOrganizationResponse200AllOfAdditionalDataFollowers {
            follower_user_id: None,
        }
    }
}


