/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetOrganizationResponse200AllOfAdditionalDataFollowersFollowerUserId : The user ID of the follower



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOrganizationResponse200AllOfAdditionalDataFollowersFollowerUserId {
    /// The ID of the follower associated with the item
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The name of the follower
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The email of the follower
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The user ID of the follower
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    /// The follower picture hash
    #[serde(rename = "pic_hash", skip_serializing_if = "Option::is_none")]
    pub pic_hash: Option<String>,
}

impl GetOrganizationResponse200AllOfAdditionalDataFollowersFollowerUserId {
    /// The user ID of the follower
    pub fn new() -> GetOrganizationResponse200AllOfAdditionalDataFollowersFollowerUserId {
        GetOrganizationResponse200AllOfAdditionalDataFollowersFollowerUserId {
            id: None,
            name: None,
            email: None,
            user_id: None,
            pic_hash: None,
        }
    }
}


