/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAssociatedFollowersResponse2001DataInner {
    /// The ID of the organization
    #[serde(rename = "org_id", skip_serializing_if = "Option::is_none")]
    pub org_id: Option<i32>,
    /// The user ID of the follower related to the item
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    /// The ID of the follower
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The date and time of adding the follower to the item
    #[serde(rename = "add_time", skip_serializing_if = "Option::is_none")]
    pub add_time: Option<String>,
}

impl GetAssociatedFollowersResponse2001DataInner {
    pub fn new() -> GetAssociatedFollowersResponse2001DataInner {
        GetAssociatedFollowersResponse2001DataInner {
            org_id: None,
            user_id: None,
            id: None,
            add_time: None,
        }
    }
}


