/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetOrganizationsResponse200AllOfRelatedObjectsPicture : The picture that is associated with the item



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOrganizationsResponse200AllOfRelatedObjectsPicture {
    #[serde(rename = "PICTURE_ID", skip_serializing_if = "Option::is_none")]
    pub picture_id: Option<Box<crate::models::GetOrganizationsResponse200AllOfRelatedObjectsPicturePictureId>>,
}

impl GetOrganizationsResponse200AllOfRelatedObjectsPicture {
    /// The picture that is associated with the item
    pub fn new() -> GetOrganizationsResponse200AllOfRelatedObjectsPicture {
        GetOrganizationsResponse200AllOfRelatedObjectsPicture {
            picture_id: None,
        }
    }
}


