/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDaysByStagesInner : The moved deals average age by the stage



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDaysByStagesInner {
    /// The stage ID
    #[serde(rename = "stage_id", skip_serializing_if = "Option::is_none")]
    pub stage_id: Option<i32>,
    /// The average deals age in specific stage
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<i32>,
}

impl GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDaysByStagesInner {
    /// The moved deals average age by the stage
    pub fn new() -> GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDaysByStagesInner {
        GetPipelineMovementStatisticsResponse200AllOfDataAverageAgeInDaysByStagesInner {
            stage_id: None,
            value: None,
        }
    }
}


