/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPersonProductsResponse200AllOfDataInner {
    #[serde(rename = "DEAL_ID", skip_serializing_if = "Option::is_none")]
    pub deal_id: Option<Box<crate::models::GetPersonProductsResponse200AllOfDataInnerDealId>>,
}

impl GetPersonProductsResponse200AllOfDataInner {
    pub fn new() -> GetPersonProductsResponse200AllOfDataInner {
        GetPersonProductsResponse200AllOfDataInner {
            deal_id: None,
        }
    }
}


