/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDealsResponse200RelatedObjects {
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<crate::models::GetDealsResponse200RelatedObjectsUser>>,
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<Box<crate::models::GetDealsResponse200RelatedObjectsOrganization>>,
    #[serde(rename = "person", skip_serializing_if = "Option::is_none")]
    pub person: Option<Box<crate::models::GetDealsResponse200RelatedObjectsPerson>>,
}

impl GetDealsResponse200RelatedObjects {
    pub fn new() -> GetDealsResponse200RelatedObjects {
        GetDealsResponse200RelatedObjects {
            user: None,
            organization: None,
            person: None,
        }
    }
}


