/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAssociatedMailMessagesResponse200AllOfDataInner {
    /// The type of the data item
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// The date and time when the item was created
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::MailMessageItemForList>>,
}

impl GetAssociatedMailMessagesResponse200AllOfDataInner {
    pub fn new() -> GetAssociatedMailMessagesResponse200AllOfDataInner {
        GetAssociatedMailMessagesResponse200AllOfDataInner {
            object: None,
            timestamp: None,
            data: None,
        }
    }
}


