/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProductFieldsResponse200 {
    /// If the response is successful or not
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    /// Array containing data for all product fields
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::ProductField>>,
    /// Additional data for the product field, such as pagination
    #[serde(rename = "additional_data", skip_serializing_if = "Option::is_none")]
    pub additional_data: Option<serde_json::Value>,
}

impl GetProductFieldsResponse200 {
    pub fn new() -> GetProductFieldsResponse200 {
        GetProductFieldsResponse200 {
            success: None,
            data: None,
            additional_data: None,
        }
    }
}


