/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListProductsResponse200AllOfRelatedObjects {
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<crate::models::GetActivitiesResponse200RelatedObjectsUser>>,
}

impl ListProductsResponse200AllOfRelatedObjects {
    pub fn new() -> ListProductsResponse200AllOfRelatedObjects {
        ListProductsResponse200AllOfRelatedObjects {
            user: None,
        }
    }
}


