/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PipelineDetailsAllOfDealsSummaryPerStagesStageId : The currency summaries per stage. This parameter is dynamic and changes according to `stage_id` value.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineDetailsAllOfDealsSummaryPerStagesStageId {
    #[serde(rename = "CURRENCY_ID", skip_serializing_if = "Option::is_none")]
    pub currency_id: Option<Box<crate::models::PipelineDetailsAllOfDealsSummaryPerStagesStageIdCurrencyId>>,
}

impl PipelineDetailsAllOfDealsSummaryPerStagesStageId {
    /// The currency summaries per stage. This parameter is dynamic and changes according to `stage_id` value.
    pub fn new() -> PipelineDetailsAllOfDealsSummaryPerStagesStageId {
        PipelineDetailsAllOfDealsSummaryPerStagesStageId {
            currency_id: None,
        }
    }
}


