/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PipelineDetailsAllOfDealsSummaryPerCurrencyFull : Full currency summaries



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineDetailsAllOfDealsSummaryPerCurrencyFull {
    #[serde(rename = "CURRENCY_ID", skip_serializing_if = "Option::is_none")]
    pub currency_id: Option<Box<crate::models::PipelineDetailsAllOfDealsSummaryPerCurrencyFullCurrencyId>>,
}

impl PipelineDetailsAllOfDealsSummaryPerCurrencyFull {
    /// Full currency summaries
    pub fn new() -> PipelineDetailsAllOfDealsSummaryPerCurrencyFull {
        PipelineDetailsAllOfDealsSummaryPerCurrencyFull {
            currency_id: None,
        }
    }
}


