/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchItemByFieldResponse200AllOfDataInner {
    /// The ID of the item
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The value of the searched `field_key`
    #[serde(rename = "$field_key", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dollar_field_key: Option<Option<serde_json::Value>>,
}

impl SearchItemByFieldResponse200AllOfDataInner {
    pub fn new() -> SearchItemByFieldResponse200AllOfDataInner {
        SearchItemByFieldResponse200AllOfDataInner {
            id: None,
            dollar_field_key: None,
        }
    }
}


