/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchPersonsResponse200AllOfDataItemsInnerItemOwner {
    /// The ID of the owner of the person
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
}

impl SearchPersonsResponse200AllOfDataItemsInnerItemOwner {
    pub fn new() -> SearchPersonsResponse200AllOfDataItemsInnerItemOwner {
        SearchPersonsResponse200AllOfDataItemsInnerItemOwner {
            id: None,
        }
    }
}


