/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchProductsResponse200AllOfData {
    /// The array of found items
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::SearchProductsResponse200AllOfDataItemsInner>>,
}

impl SearchProductsResponse200AllOfData {
    pub fn new() -> SearchProductsResponse200AllOfData {
        SearchProductsResponse200AllOfData {
            items: None,
        }
    }
}


