/*
 * Pipedrive API v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateStageRequest {
    /// The name of the stage
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The ID of the pipeline to add stage to
    #[serde(rename = "pipeline_id", skip_serializing_if = "Option::is_none")]
    pub pipeline_id: Option<i32>,
    /// The success probability percentage of the deal. Used/shown when deal weighted values are used.
    #[serde(rename = "deal_probability", skip_serializing_if = "Option::is_none")]
    pub deal_probability: Option<i32>,
    /// Whether deals in this stage can become rotten
    #[serde(rename = "rotten_flag", skip_serializing_if = "Option::is_none")]
    pub rotten_flag: Option<bool>,
    /// The number of days the deals not updated in this stage would become rotten. Applies only if the `rotten_flag` is set.
    #[serde(rename = "rotten_days", skip_serializing_if = "Option::is_none")]
    pub rotten_days: Option<i32>,
    /// An order number for this stage. Order numbers should be used to order the stages in the pipeline.
    #[serde(rename = "order_nr", skip_serializing_if = "Option::is_none")]
    pub order_nr: Option<i32>,
}

impl UpdateStageRequest {
    pub fn new() -> UpdateStageRequest {
        UpdateStageRequest {
            name: None,
            pipeline_id: None,
            deal_probability: None,
            rotten_flag: None,
            rotten_days: None,
            order_nr: None,
        }
    }
}


