name: CI

on:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule: [cron: "00 1 1 * *"]

permissions:
  contents: read

jobs:
  # test:
  #   name: Test suite
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 45
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: dtolnay/rust-toolchain@nightly
  #     - run: cd test_suite && cargo test --features unstable

  stable:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta]
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - run: cargo build

  publish:
    if: ${{ github.ref_type == 'tag' }} # runs only on tags like v0.0.1
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - run: cargo build
      - run: cargo publish --token ${CRATES_TOKEN}
    env:
      CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@clippy
      - run: cargo clippy
